AWSTemplateFormatVersion: 2010-09-09


Description: Operative platform for a real estate marketplace


Resources:

  DatabaseCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      GenerateSecretString:
        ExcludeCharacters: '"@/\'
        GenerateStringKey: password
        PasswordLength: 16
        SecretStringTemplate: '{"username": "master"}'

  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: "20"
      DBInstanceClass: db.t3.micro
      Engine: postgres
      MasterUsername: !Join [ '', [ '{{resolve:secretsmanager:', !Ref DatabaseCredentials, ':SecretString:username}}' ] ]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref DatabaseCredentials, ':SecretString:password}}' ]]
