AWSTemplateFormatVersion: 2010-09-09


Description: Operative platform for a real estate marketplace


Resources:

  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: "20"
      DBInstanceClass: db.t3.micro
      Engine: postgres
      MasterUsername: master
