name: marketplace
version: 1.0.0
config-version: 2

profile: default

models:
  marketplace:
    materialized: table

seeds:
  +quote_columns: false
  +schema: seeds
  marketplace:
    kc_house_data:
      +column_types:
        id: varchar(16)
        date: timestamp
