AWSTemplateFormatVersion: 2010-09-09


Description: Deployment pipelines


Parameters:

  CodeStarSourceConnectionArn:
    Type: String

  CodeStarSourceConnectionBranchName:
    Type: String

  CodeStarSourceConnectionFullRepositoryId:
    Type: String

  ProjectName:
    Type: String


Resources:

  ArtifactStore:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::AccountId}-${AWS::StackName}-artifact-store

  CloudFormationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: cloudformation.amazonaws.com
      Policies:
        - PolicyName: ManageResources
          PolicyDocument:
            Statement:
              Action:
                - ec2:DescribeAccountAttributes
                - ec2:DescribeSecurityGroups
                - rds:CreateDBInstance
                - rds:DeleteDBInstance
                - rds:DescribeDBInstances
                - rds:ModifyDBInstance
                - secretsmanager:CreateSecret
                - secretsmanager:DeleteSecret
                - secretsmanager:GetRandomPassword
                - secretsmanager:GetSecretValue
                - secretsmanager:PutSecretValue
                - secretsmanager:TagResource
                - secretsmanager:UntagResource
                - secretsmanager:UpdateSecret
              Effect: Allow
              Resource: "*"
        - PolicyName: CreateServiceLinkedRoleForRDS
          # cf. https://docs.aws.amazon.com/IAM/latest/UserGuide/using-service-linked-roles.html#service-linked-role-permissions
          PolicyDocument:
            Statement:
              - Action: iam:CreateServiceLinkedRole
                Condition:
                  StringLike:
                    iam:AWSServiceName: rds.amazonaws.com
                Effect: Allow
                Resource: arn:aws:iam::*:role/aws-service-role/rds.amazonaws.com/AWSServiceRoleForRDS*
              - Action:
                  - iam:AttachRolePolicy,
                  - iam:PutRolePolicy
                Effect: Allow
                Resource: arn:aws:iam::*:role/aws-service-role/rds.amazonaws.com/AWSServiceRoleForRDS*


  MarketPlacePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactStore
      RoleArn: !GetAtt PipelineRole.Arn
      Stages:
        - Name: Source
          Actions:
            - Name: PullRepoFromGitHub
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: "1"
              Configuration:
                BranchName: !Ref CodeStarSourceConnectionBranchName
                ConnectionArn: !Ref CodeStarSourceConnectionArn
                FullRepositoryId: !Ref CodeStarSourceConnectionFullRepositoryId
              OutputArtifacts:
                - Name: repo
        - Name: Deploy
          Actions:
            - Name: DeployStackMarketplace
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !GetAtt CloudFormationRole.Arn
                StackName: !Sub ${ProjectName}-200-marketplace
                TemplatePath: repo::200-marketplace/cloudformation.yml
              InputArtifacts:
                - Name: repo

  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: codepipeline.amazonaws.com
      Policies:
        - PolicyName: ManageCloudFormationStacks
          PolicyDocument:
            Statement:
              Action:
                - cloudformation:CreateStack
                - cloudformation:DescribeStacks
                - cloudformation:UpdateStack
              Effect: Allow
              Resource: !Sub arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${ProjectName}-*/*
        - PolicyName: UseCodeStarConnection
          PolicyDocument:
            Statement:
              Action: codestar-connections:UseConnection
              Effect: Allow
              Resource: !Ref CodeStarSourceConnectionArn
        - PolicyName: PassCloudFormationRole
          PolicyDocument:
            Statement:
              Action: iam:PassRole
              Effect: Allow
              Resource: !GetAtt CloudFormationRole.Arn
        - PolicyName: ReadAndWriteArtifacts
          PolicyDocument:
            Statement:
              Action:
                - s3:GetObject
                - s3:GetObjectVersion
                - s3:PutObject
                - s3:PutObjectAcl
              Effect: Allow
              Resource: !Sub ${ArtifactStore.Arn}/*
