AWSTemplateFormatVersion: 2010-09-09


Description: Deployment pipelines


Parameters:

  CodeStarSourceConnectionArn:
    Type: String

  CodeStarSourceConnectionBranchName:
    Type: String

  CodeStarSourceConnectionFullRepositoryId:
    Type: String


Resources:

  ArtifactStore:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::AccountId}-${AWS::StackName}-artifact-store

  CloudFormationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: cloudformation.amazonaws.com

  MarketPlacePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactStore
      RoleArn: !GetAtt PipelineRole.Arn
      Stages:
        - Name: Source
          Actions:
            - Name: PullRepoFromGitHub
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: "1"
              Configuration:
                BranchName: !Ref CodeStarSourceConnectionBranchName
                ConnectionArn: !Ref CodeStarSourceConnectionArn
                FullRepositoryId: !Ref CodeStarSourceConnectionFullRepositoryId
              OutputArtifacts:
                - Name: repo
        - Name: Deploy
          Actions:
            - Name: DeployStackMarketplace
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !GetAtt CloudFormationRole.Arn
                StackName: !Ref MarketplaceStackName
                TemplateConfiguration: repo::share/configuration.cloudformation.json
                TemplatePath: repo::200-marketplace/cloudformation.yml
              InputArtifacts:
                - Name: repo

  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: codepipeline.amazonaws.com
      Policies:
        - PolicyName: CreateCloudFormationStacks
          PolicyDocument:
            Statement:
              Action:
                - cloudformation:CreateStack
                - cloudformation:DescribeStacks
              Effect: Allow
              Resource: !Sub arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/*/*
        - PolicyName: UseCodeStarConnection
          PolicyDocument:
            Statement:
              Action: codestar-connections:UseConnection
              Effect: Allow
              Resource: !Ref CodeStarSourceConnectionArn
        - PolicyName: PassCloudFormationRole
          PolicyDocument:
            Statement:
              Action: iam:PassRole
              Effect: Allow
              Resource: !GetAtt CloudFormationRole.Arn
        - PolicyName: ReadAndWriteArtifacts
          PolicyDocument:
            Statement:
              Action:
                - s3:GetObject
                - s3:GetObjectVersion
                - s3:PutObject
                - s3:PutObjectAcl
              Effect: Allow
              Resource: !Sub ${ArtifactStore.Arn}/*
