default:
  outputs:
    prod:
      type: postgres
      threads: 4
      host: "{{ env_var('MP_DB_HOST') }}"
      port: "{{ env_var('MP_DB_PORT') }}"
      user: "{{ env_var('MP_DB_USER') }}"
      pass: "{{ env_var('MP_DB_PASSWORD') }}"
      dbname: postgres
      schema: marketplace
  target: prod
